[package]
name = "rust-winxp-nostd-example"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.61.0", features = ["Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

